/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;

/**/
public class VGCatElectrodomesticos extends javax.swing.JFrame {

    /**
     * Creates new form VGCatElectrodomesticos
     */
    public Controller controlador;
    public VGCatElectrodomesticos(Controller controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIngresarCatElectrodomestico = new javax.swing.JButton();
        btnEditarCatElectrodomestico = new javax.swing.JButton();
        btnConsultarCatElectrodomesticos = new javax.swing.JButton();
        btnInactivarCatElectrodomestico = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Categorías de Electrodomésticos");

        btnIngresarCatElectrodomestico.setText("Ingresar Categoría de Electrodoméstico");
        btnIngresarCatElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCatElectrodomesticoActionPerformed(evt);
            }
        });

        btnEditarCatElectrodomestico.setText("Editar Categoría de Electrodoméstico");
        btnEditarCatElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatElectrodomesticoActionPerformed(evt);
            }
        });

        btnConsultarCatElectrodomesticos.setText("Consultar Categorías de Electrodomésticos");
        btnConsultarCatElectrodomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCatElectrodomesticosActionPerformed(evt);
            }
        });

        btnInactivarCatElectrodomestico.setText("Desactivar Categoría de Electrodoméstico");
        btnInactivarCatElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarCatElectrodomesticoActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnIngresarCatElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCatElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCatElectrodomesticos)
                    .addComponent(btnInactivarCatElectrodomestico)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(btnIngresarCatElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnEditarCatElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnConsultarCatElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnInactivarCatElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarCatElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCatElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VGUIngresarCatElectrodomestico vtnIngresarCatElectrodomestico = new VGUIngresarCatElectrodomestico(controlador);
        vtnIngresarCatElectrodomestico.setVisible(true);
    }//GEN-LAST:event_btnIngresarCatElectrodomesticoActionPerformed

    private void btnEditarCatElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VSolicitarEdicion vtnSolicitarEdicion = new VSolicitarEdicion(controlador, TipoSolicitud.CATELECTRODOMESTICO);
        vtnSolicitarEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditarCatElectrodomesticoActionPerformed

    private void btnConsultarCatElectrodomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCatElectrodomesticosActionPerformed
        // TODO add your handling code here:
        VGUConsultarCatElectrodomesticos vtnConsultarCatElectrodomesticos = new VGUConsultarCatElectrodomesticos(controlador);
        vtnConsultarCatElectrodomesticos.setVisible(true);
    }//GEN-LAST:event_btnConsultarCatElectrodomesticosActionPerformed

    private void btnInactivarCatElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarCatElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VSolicitarInactivacion vtnInactivacion = new VSolicitarInactivacion(controlador, TipoSolicitud.CATELECTRODOMESTICO);
        vtnInactivacion.setVisible(true);
    }//GEN-LAST:event_btnInactivarCatElectrodomesticoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarCatElectrodomesticos;
    private javax.swing.JButton btnEditarCatElectrodomestico;
    private javax.swing.JButton btnInactivarCatElectrodomestico;
    private javax.swing.JButton btnIngresarCatElectrodomestico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
