/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;

/**/
public class VGElectrodomesticos extends javax.swing.JFrame {

    /**
     * Creates new form VGElectrodomesticos
     */
    public Controller controlador;
    public VGElectrodomesticos(Controller controlador) {
        this.controlador =  controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        btnIngresarElectrodomestico = new javax.swing.JButton();
        btnEditarElectrodomestico = new javax.swing.JButton();
        btnConsultarElectrodomesticos = new javax.swing.JButton();
        btnInactivarElectrodomestico = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Gestión de Electrodomésticos");

        btnIngresarElectrodomestico.setText("Ingresar Electrodoméstico");
        btnIngresarElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarElectrodomesticoActionPerformed(evt);
            }
        });

        btnEditarElectrodomestico.setText("Editar Electrodoméstico");
        btnEditarElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarElectrodomesticoActionPerformed(evt);
            }
        });

        btnConsultarElectrodomesticos.setText("Consultar Electrodomésticos");
        btnConsultarElectrodomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarElectrodomesticosActionPerformed(evt);
            }
        });

        btnInactivarElectrodomestico.setText("Desactivar Electrodoméstico");
        btnInactivarElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarElectrodomesticoActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnConsultarElectrodomesticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInactivarElectrodomestico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresarElectrodomestico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarElectrodomestico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(mainLabel)
                .addGap(37, 37, 37)
                .addComponent(btnIngresarElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnEditarElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnConsultarElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnInactivarElectrodomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInactivarElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VSolicitarInactivacion vtnInactivacion = new VSolicitarInactivacion(controlador, TipoSolicitud.ELECTRODOMESTICO);
        vtnInactivacion.setVisible(true);
    }//GEN-LAST:event_btnInactivarElectrodomesticoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEditarElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VSolicitarEdicion vtnSolicitarEdicion = new VSolicitarEdicion(controlador, TipoSolicitud.ELECTRODOMESTICO);
        vtnSolicitarEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditarElectrodomesticoActionPerformed

    private void btnIngresarElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarElectrodomesticoActionPerformed
        // TODO add your handling code here:
        VGUIngresarElectrodomestico vtnIngresarElectrodomestico = new VGUIngresarElectrodomestico(controlador);
        vtnIngresarElectrodomestico.setVisible(true);
    }//GEN-LAST:event_btnIngresarElectrodomesticoActionPerformed

    private void btnConsultarElectrodomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarElectrodomesticosActionPerformed
        // TODO add your handling code here:
        VGUConsultarElectrodomesticos vtnConsultarElectrodomesticos = new VGUConsultarElectrodomesticos(controlador);
        vtnConsultarElectrodomesticos.setVisible(true);
    }//GEN-LAST:event_btnConsultarElectrodomesticosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarElectrodomesticos;
    private javax.swing.JButton btnEditarElectrodomestico;
    private javax.swing.JButton btnInactivarElectrodomestico;
    private javax.swing.JButton btnIngresarElectrodomestico;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
