/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;

/**/
public class VGSucursales extends javax.swing.JFrame {

    /**
     * Creates new form VMSucursales
     */
    public Controller controlador;
    public VGSucursales(Controller controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        btnIngresarSucursal = new javax.swing.JButton();
        btnEditarSucursal = new javax.swing.JButton();
        btnConsultarSucursales = new javax.swing.JButton();
        btnInactivarSucursal = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Gestión de Sucursales");

        btnIngresarSucursal.setText("Ingresar Sucursal");
        btnIngresarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarSucursalActionPerformed(evt);
            }
        });

        btnEditarSucursal.setText("Editar Sucursal");
        btnEditarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSucursalActionPerformed(evt);
            }
        });

        btnConsultarSucursales.setText("Consultar Sucursales");
        btnConsultarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSucursalesActionPerformed(evt);
            }
        });

        btnInactivarSucursal.setText("Desactivar Sucursal");
        btnInactivarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarSucursalActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(mainLabel)
                    .addComponent(btnIngresarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInactivarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mainLabel)
                .addGap(46, 46, 46)
                .addComponent(btnIngresarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnEditarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnConsultarSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnInactivarSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEditarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSucursalActionPerformed
        // TODO add your handling code here:
        VSolicitarEdicion vtnSolicitarEdicion = new VSolicitarEdicion(controlador, TipoSolicitud.SUCURSAL);
        vtnSolicitarEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditarSucursalActionPerformed

    private void btnConsultarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSucursalesActionPerformed
        // TODO add your handling code here:
        VGUConsultarSucursales vtnConsultarSucursales = new VGUConsultarSucursales(controlador);
        vtnConsultarSucursales.setVisible(true);
    }//GEN-LAST:event_btnConsultarSucursalesActionPerformed

    private void btnInactivarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarSucursalActionPerformed
        // TODO add your handling code here:
        VSolicitarInactivacion vtnInactivacion = new VSolicitarInactivacion(controlador, TipoSolicitud.SUCURSAL);
        vtnInactivacion.setVisible(true);
    }//GEN-LAST:event_btnInactivarSucursalActionPerformed

    private void btnIngresarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarSucursalActionPerformed
        // TODO add your handling code here:
        VGUIngresarSucursal vtnIngresarSucursal = new VGUIngresarSucursal(controlador);
        vtnIngresarSucursal.setVisible(true);
    }//GEN-LAST:event_btnIngresarSucursalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarSucursales;
    private javax.swing.JButton btnEditarSucursal;
    private javax.swing.JButton btnInactivarSucursal;
    private javax.swing.JButton btnIngresarSucursal;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
