/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;

/**/
public class VMCatalogos extends javax.swing.JFrame {

    /**
     * Creates new form VMCatalogos
     */
    public Controller controlador;
    public VMCatalogos(Controller controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGestionSucursales = new javax.swing.JButton();
        btnGestionElectrodomesticos = new javax.swing.JButton();
        btnGestionCatElectrodomesticos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manejo de Catálogos");
        jLabel1.setMaximumSize(new java.awt.Dimension(164, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(164, 23));
        jLabel1.setPreferredSize(new java.awt.Dimension(164, 23));

        btnGestionSucursales.setText("Gestión de Sucursales");
        btnGestionSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionSucursalesActionPerformed(evt);
            }
        });

        btnGestionElectrodomesticos.setText("Gestión de Electrodomésticos");
        btnGestionElectrodomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionElectrodomesticosActionPerformed(evt);
            }
        });

        btnGestionCatElectrodomesticos.setText("Gestión de Categorías de Electrodomésticos");
        btnGestionCatElectrodomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionCatElectrodomesticosActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionCatElectrodomesticos)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnGestionSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGestionElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGestionCatElectrodomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionSucursalesActionPerformed
        // TODO add your handling code here:
        VGSucursales vtnSucursales = new VGSucursales(controlador);
        vtnSucursales.setVisible(true);
    }//GEN-LAST:event_btnGestionSucursalesActionPerformed

    private void btnGestionElectrodomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionElectrodomesticosActionPerformed
        // TODO add your handling code here:
        VGElectrodomesticos vtnElectrodomesticos = new VGElectrodomesticos(controlador);
        vtnElectrodomesticos.setVisible(true);
    }//GEN-LAST:event_btnGestionElectrodomesticosActionPerformed

    private void btnGestionCatElectrodomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCatElectrodomesticosActionPerformed
        // TODO add your handling code here:
        VGCatElectrodomesticos vtnCatElectrodomesticos = new VGCatElectrodomesticos(controlador);
        vtnCatElectrodomesticos.setVisible(true);
    }//GEN-LAST:event_btnGestionCatElectrodomesticosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGestionCatElectrodomesticos;
    private javax.swing.JButton btnGestionElectrodomesticos;
    private javax.swing.JButton btnGestionSucursales;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
