/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;

/**/
public class VMClientes extends javax.swing.JFrame {

    /**
     * Creates new form VMClientes
     */
    public Controller controlador;
    public VMClientes(Controller controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        btnIngresarCliente = new javax.swing.JButton();
        btnEditarClientes = new javax.swing.JButton();
        btnConsultarClientes = new javax.swing.JButton();
        btnInactivarCliente = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Manejo de Clientes");

        btnIngresarCliente.setText("Ingresar Cliente");
        btnIngresarCliente.setLocation(new java.awt.Point(-32500, -32729));
        btnIngresarCliente.setMaximumSize(new java.awt.Dimension(139, 23));
        btnIngresarCliente.setMinimumSize(new java.awt.Dimension(139, 23));
        btnIngresarCliente.setPreferredSize(new java.awt.Dimension(139, 23));
        btnIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarClienteActionPerformed(evt);
            }
        });

        btnEditarClientes.setText("Editar Cliente");
        btnEditarClientes.setLocation(new java.awt.Point(-32500, -32729));
        btnEditarClientes.setMaximumSize(new java.awt.Dimension(139, 23));
        btnEditarClientes.setMinimumSize(new java.awt.Dimension(139, 23));
        btnEditarClientes.setPreferredSize(new java.awt.Dimension(139, 23));
        btnEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClientesActionPerformed(evt);
            }
        });

        btnConsultarClientes.setText("Consultar Clientes");
        btnConsultarClientes.setLocation(new java.awt.Point(-32500, -32729));
        btnConsultarClientes.setMaximumSize(new java.awt.Dimension(139, 23));
        btnConsultarClientes.setMinimumSize(new java.awt.Dimension(139, 23));
        btnConsultarClientes.setPreferredSize(new java.awt.Dimension(139, 23));
        btnConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientesActionPerformed(evt);
            }
        });

        btnInactivarCliente.setText("Desactivar Cliente");
        btnInactivarCliente.setLocation(new java.awt.Point(-32500, -32729));
        btnInactivarCliente.setMaximumSize(new java.awt.Dimension(139, 23));
        btnInactivarCliente.setMinimumSize(new java.awt.Dimension(139, 23));
        btnInactivarCliente.setPreferredSize(new java.awt.Dimension(139, 23));
        btnInactivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarClienteActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setLocation(new java.awt.Point(-32500, -32729));
        btnCerrar.setMaximumSize(new java.awt.Dimension(139, 23));
        btnCerrar.setMinimumSize(new java.awt.Dimension(139, 23));
        btnCerrar.setPreferredSize(new java.awt.Dimension(139, 23));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnConsultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInactivarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLabel)
                    .addComponent(btnIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(mainLabel)
                .addGap(47, 47, 47)
                .addComponent(btnIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEditarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnConsultarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnInactivarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarClienteActionPerformed
        // TODO add your handling code here:
        VMUIngresarCliente vtnIngresarCliente = new VMUIngresarCliente(controlador);
        vtnIngresarCliente.setVisible(true);
       
    }//GEN-LAST:event_btnIngresarClienteActionPerformed

    private void btnEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClientesActionPerformed
        // TODO add your handling code here:
        VSolicitarEdicion vtnSolicitarEdicion = new VSolicitarEdicion(controlador, TipoSolicitud.CLIENTE);
        vtnSolicitarEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditarClientesActionPerformed

    private void btnConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientesActionPerformed
        // TODO add your handling code here:
        VMUConsultarClientes vtnConsultarClientes = new VMUConsultarClientes(controlador);
        vtnConsultarClientes.setVisible(true);
    }//GEN-LAST:event_btnConsultarClientesActionPerformed

    private void btnInactivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarClienteActionPerformed
        // TODO add your handling code here:
        VSolicitarInactivacion vtnInactivacion = new VSolicitarInactivacion(controlador, TipoSolicitud.CLIENTE);
        vtnInactivacion.setVisible(true);
    }//GEN-LAST:event_btnInactivarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarClientes;
    private javax.swing.JButton btnEditarClientes;
    private javax.swing.JButton btnInactivarCliente;
    private javax.swing.JButton btnIngresarCliente;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
