/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;


public class VMFacturacion extends javax.swing.JFrame {

    /**
     * Creates new form VMFacturacion
     */
    public Controller controlador;
    public VMFacturacion(Controller controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();
        btnCrearFactura = new javax.swing.JButton();
        btnAnularFactura = new javax.swing.JButton();
        btnConsultarFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrar.setText("Cerrar");
        btnCerrar.setLocation(new java.awt.Point(-32500, -32729));
        btnCerrar.setMaximumSize(new java.awt.Dimension(139, 23));
        btnCerrar.setMinimumSize(new java.awt.Dimension(139, 23));
        btnCerrar.setPreferredSize(new java.awt.Dimension(139, 23));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Facturación");

        btnCrearFactura.setText("Crear Factura");
        btnCrearFactura.setLocation(new java.awt.Point(-32500, -32729));
        btnCrearFactura.setMaximumSize(new java.awt.Dimension(139, 23));
        btnCrearFactura.setMinimumSize(new java.awt.Dimension(139, 23));
        btnCrearFactura.setPreferredSize(new java.awt.Dimension(139, 23));
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        btnAnularFactura.setText("Anular Factura");
        btnAnularFactura.setLocation(new java.awt.Point(-32500, -32729));
        btnAnularFactura.setMaximumSize(new java.awt.Dimension(139, 23));
        btnAnularFactura.setMinimumSize(new java.awt.Dimension(139, 23));
        btnAnularFactura.setPreferredSize(new java.awt.Dimension(139, 23));
        btnAnularFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularFacturaActionPerformed(evt);
            }
        });

        btnConsultarFactura.setText("Consultar Facturas");
        btnConsultarFactura.setLocation(new java.awt.Point(-32500, -32729));
        btnConsultarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnConsultarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLabel)
                    .addComponent(btnCrearFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnularFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(mainLabel)
                .addGap(47, 47, 47)
                .addComponent(btnCrearFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAnularFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnConsultarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
        // TODO add your handling code here:
        VMUIngresarFactura vtnIngresarFactura= new VMUIngresarFactura(controlador);
        vtnIngresarFactura.setVisible(true);

    }//GEN-LAST:event_btnCrearFacturaActionPerformed

    private void btnAnularFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularFacturaActionPerformed
        // TODO add your handling code here:
        VSolicitarInactivacion vtnInactivacion = new VSolicitarInactivacion(controlador, TipoSolicitud.FACTURACION);
        vtnInactivacion.setVisible(true);
    }//GEN-LAST:event_btnAnularFacturaActionPerformed

    private void btnConsultarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFacturaActionPerformed
        // TODO add your handling code here:
        VMUConsultarFactura vtnConsultarFactura = new VMUConsultarFactura(controlador);
        vtnConsultarFactura.setVisible(true);
    }//GEN-LAST:event_btnConsultarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularFactura;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarFactura;
    private javax.swing.JButton btnCrearFactura;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables
}
