/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controller.Controller;
import Objects.ApplianceCategory;
import Objects.Client;
import Objects.Appliance;
import Objects.Employee;
import Objects.Branch;
import javax.swing.JOptionPane;

/**
 *
 */
public class VSolicitarEdicion extends javax.swing.JFrame {

    /**
     * Creates new form VSolicitarEdicion
     */
    public Controller controlador;
    public TipoSolicitud solicitud;
    
    public VSolicitarEdicion(Controller controlador, TipoSolicitud solicitud) {
        this.controlador = controlador;
        this.solicitud = solicitud;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain2 = new javax.swing.JLabel();
        inptNombre = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblMain1 = new javax.swing.JLabel();

        setResizable(false);

        lblMain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMain2.setText("Para editar sucursales, categorías de electrodomésticos o electrodomésticos, ingrese el nombre.");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cancelar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblMain1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMain1.setText("Para editar clientes o empleados, ingrese el nombre de usuario.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(23, 23, 23)
                        .addComponent(btnCerrar)))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblMain1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(lblMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inptNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnCerrar))
                .addGap(17, 17, 17))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(lblMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String nickname = inptNombre.getText();
        
        switch(solicitud){
            case EMPLEADO:
                Employee empleado = controlador.consultarEmpleado(nickname);
                if (empleado != null){
                    VMUEditarEmpleado vtnEditarEmpleado = new VMUEditarEmpleado(controlador, empleado);
                    vtnEditarEmpleado.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario que mencionó no se encontró.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case CLIENTE:
                Client cliente = controlador.consultarCliente(nickname);
                if (cliente != null){
                    VMUEditarCliente vtnEditarCliente = new VMUEditarCliente(controlador, cliente);
                    vtnEditarCliente.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario que mencionó no se encontró.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case SUCURSAL:
                Branch sucursal = controlador.consultarSucursal(nickname);
                if (sucursal != null){
                    VGUEditarSucursal vtnEditarSucursal = new VGUEditarSucursal(controlador, sucursal);
                    vtnEditarSucursal.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario que mencionó no se encontró.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case CATELECTRODOMESTICO:
                ApplianceCategory categoriaElectrodomestico = controlador.consultarCategoriaElectrodomestico(nickname);
                if (categoriaElectrodomestico != null){
                    VGUEditarCatElectrodomestico vtnEditarCatElectrodomestico = new VGUEditarCatElectrodomestico(controlador, categoriaElectrodomestico);
                    vtnEditarCatElectrodomestico.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario que mencionó no se encontró.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case ELECTRODOMESTICO:
                Appliance electrodomestico = controlador.consultarElectrodomestico(nickname);
                if (electrodomestico != null){
                    VGUEditarElectrodomestico vtnEditarElectrodomestico = new VGUEditarElectrodomestico(controlador, electrodomestico);
                    vtnEditarElectrodomestico.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario que mencionó no se encontró.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
                
                
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JTextField inptNombre;
    private javax.swing.JLabel lblMain1;
    private javax.swing.JLabel lblMain2;
    // End of variables declaration//GEN-END:variables
}
